---
- name: "check for running container"
  command: >
    docker inspect --format \{\{.State.Running\}\} das_vault
  ignore_errors: True
  changed_when: no
  register: vault_container_check
- name: "run container"
  become: no
  delegate_to: 'localhost'
  docker_container:
    name: "{{vault_docker_name}}"
    docker_host: "tcp://{{vault_docker_host}}:2376"
    cacert_path: "{{vault_docker_cacert_path}}"
    key_path: "{{vault_docker_key_path}}"
    cert_path:  "{{vault_docker_cert_path}}"
    tls_hostname: "{{vault_docker_host}}"
    tls: yes
    recreate: "yes"
    published_ports:
      - "{{vault_internal_ip}}:{{vault_port}}:8200"
    image: "vault:{{vault_version}}"
    command: "server"
    volumes:
      - "{{vault_config_path}}:/vault/config"
      - "{{vault_log_path}}:/vault/logs"
    capabilities:
      - "IPC_LOCK"
  when: >
    (vault_container_check.rc == 1 or
    vault_container_check.stdout == "false" or
    vault_config.changed|default(False) or
    vault_tls_bits.changed)
