- debug:
    msg: "Trying to manifest a Vault {{vault_type}}"
- include: "pre.yml"
- include: "package.yml"
  when: >
    vault_type != "docker" and
    ( vault_type == "client" or vault_type == "server" )
- include: "server.yml"
  when: vault_type == "server" or vault_type == "docker"
- include: "ui.yml"
  when: vault_type == "ui"  
- include: "workstation.yml"
  when: vault_workstation
- include: "ssh.yml"
  when: vault_ssh
- name: "set workstation vaultrc format"
  set_fact:
    vault_rc: "{{vault_profile_path}}/.vaultrc"
  when: vault_workstation
- name: "set global vaultrc format"
  set_fact:
    vault_rc: "{{vault_profile_path}}/vault_profile"
  when: "not vault_workstation"
- name: "render vaultrc"
  template:
    src: "vault-rc.j2"
    dest: "{{vault_rc}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "0660"
  when: >
    vault_workstation or vault_type == "client" or vault_type == "server"
    
