---
- include_tasks: "pre.yml"

- include_tasks: "package.yml"
  when: "vault_type != 'docker'"

- include_tasks: "server.yml"
  when: "vault_type != 'client'"

- include_tasks: "docker.yml"
  when: "vault_type == 'docker'"

- include_tasks: "service.yml"
  when: "vault_type == 'server'"

- include_tasks: "workstation.yml"
  when: vault_workstation

- name: "set workstation vaultrc format"
  set_fact:
    vault_rc: "{{vault_profile_path}}/.vaultrc"
    vaultrc_user: "{{vault_user}}"
    vaultrc_group: "{{vault_group}}"
    vaultrc_mode: "{{vault_file_mode}}"
  when: vault_workstation

- name: "set global vaultrc format"
  set_fact:
    vault_rc: "/etc/profile.d/vault_profile.sh"
    vaultrc_user: "root"
    vaultrc_group: "root"
    vaultrc_mode: "{{vault_profile_mode}}"
  when: not vault_workstation

- name: "render vaultrc"
  template:
    src: "vault-rc.j2"
    dest: "{{vault_rc}}"
    owner: "{{vaultrc_user}}"
    group: "{{vaultrc_group}}"
    mode: "{{vaultrc_mode}}"
  when: "vault_workstation or vault_type != 'docker'"
