---
- name: "create directories"
  file:
    path: "{{item}}"
    state: "directory"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "{{vault_dir_mode}}"
  with_items:
    - "{{vault_bin_path}}"
    - "{{vault_install_directory}}"

- name: "download vault binary"
  get_url:
    url: "{{vault_download_url}}"
    dest: "{{vault_download_dest}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "{{vault_file_mode}}"

- name: "extract zip"
  unarchive:
    src: "{{vault_cache}}/vault-{{vault_version}}.zip"
    dest: "{{vault_install_directory}}"
    creates: "{{vault_binary}}"
    copy: "no"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "{{vault_file_mode}}"

- name: "ensure permissions"
  file:
    path: "{{vault_binary}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "{{vault_bin_mode}}"

- name: "check for existing binary"
  stat:
    path: "{{vault_bin_path}}/vault"
  register: vault_binary_existing

- name: "remove non-symlink binary location"
  file:
    path: "{{vault_bin_path}}/vault"
    state: "absent"
  when: not vault_binary_existing.stat.islnk

- name: "link binary"
  file:
    state: "link"
    path: "{{vault_bin_path}}/vault"
    src: "{{vault_binary}}"
  register: vault_binary_copy
