---
- name: "create directories"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{vault_bin_path}}"
    - "{{vault_install_directory}}"

- name: "check for existing binary"
  stat:
    path: "{{vault_binary}}"
  register: vault_binary_exists

- name: "download vault binary"
  get_url:
    url: "{{vault_download_url}}"
    dest: "{{vault_download_dest}}"
    mode: "0600"
  when: "vault_binary_exists.stat.exists == False"

- name: "extract zip"
  unarchive:
    src: "{{vault_cache}}/vault-{{vault_version}}.zip"
    dest: "{{vault_install_directory}}"
    creates: "{{vault_binary}}"
    copy: "no"
  when: "vault_binary_exists.stat.exists == False"
  register: vault_binary_extract

- name: "copy binary"
  copy:
    dest: "{{vault_bin_path}}/vault"
    src: "{{vault_binary}}"
    remote_src: true
    force: yes
  when: vault_binary_extract.changed
