- set_fact:
    vault_download_url: "{{vault_pre_url}}{{ansible_system|lower}}_amd64.zip"
  when: "ansible_machine == 'x86_64'"
- name: "install some prereqs"
  apt:
    pkg: "{{item}}"
    state: "latest"
  with_items: "{{vault_docker_apt}}"
  when: vault_type == "docker"
