---
- name: "ensure vault config directory exists"
  file:
    path: "{{vault_config_path}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "{{vault_dir_mode}}"
    state: "directory"

- name: "generate configuration"
  template:
    src: "config.hcl"
    dest: "{{vault_config_path}}/config.hcl"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "{{vault_file_mode}}"
  register: vault_config
  no_log: "{{vault_nolog}}"

- name: "create log directory"
  file:
    path: "{{vault_log_path}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "{{vault_log_mode}}"
    state: "directory"

- name: "copy tls bits from vault"
  copy:
    dest: "{{item.dest}}"
    content: "{{lookup('hashi_vault', item.src)}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "0600"
  no_log: "{{vault_nolog}}"
  loop:
    - dest: "{{vault_config_path}}/server.crt"
      src: "{{vault_cert_path}}"
    - dest: "{{vault_config_path}}/server.key"
      src: "{{vault_key_path}}"
  when: vault_cert_source == 'vault'
  register: vault_tls_vault_bits

- name: "copy tls bits from files"
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "0600"
  no_log: "{{vault_nolog}}"
  loop:
    - dest: "{{vault_config_path}}/server.crt"
      src: "{{vault_cert_path}}"
    - dest: "{{vault_config_path}}/server.key"
      src: "{{vault_key_path}}"
  register: vault_tls_file_bits
  when: vault_cert_source == 'file'
