---
- name: "ensure vault config directory exists"
  file:
    path: "{{vault_config_path}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "0770"
    state: "directory"
- name: "generate configuration"
  template:
    src: "config.hcl"
    dest: "{{vault_config_path}}/config.hcl"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "0660"
  register: vault_config
- name: "create log directory"
  file:
    path: "{{vault_log_path}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "2770"
    state: "directory"
# why is this here? do the perms just break sometimes?
- name: "ensure permissions are fine"
  file:
    path: "{{vault_log_path}}/audit.log"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "0660"
    state: "file"
  ignore_errors: true
- name: "copy tls bits"
  copy:
    src: "{{dotfiles}}/vault/{{vault_cert}}.{{item}}"
    dest: "{{vault_config_path}}/server.{{item}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "0600"
  with_items:
    - "crt"
    - "key"
  register: vault_tls_bits
