- include_tasks: "network.yml"
- name: "ensure s3 bucket"
  become: no
  delegate_to: 'localhost'
  aws_s3:
    bucket: "{{vault_bucket}}"
    mode: "create"
    region: "{{vault_aws_region}}"
- name: "ensure vault config directory exists"
  file:
    path: "{{vault_config_path}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "0770"
    state: "directory"
- name: "generate configuration"
  template:
    src: "config.hcl"
    dest: "{{vault_config_path}}/config.hcl"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "0660"
  register: vault_config
- name: "create log directory"
  file:
    path: "{{vault_log_path}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "2770"
    state: "directory"
# why is this here? do the perms just break sometimes?
- name: "ensure permissions are fine"
  file:
    path: "{{vault_log_path}}/audit.log"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "0660"
    state: "file"
  ignore_errors: true
- name: "copy tls pieces"
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "0600"
  with_items: "{{vault_tls_files}}"
  register: vault_tls_bits
- include_tasks: "docker_volume.yml"
  vars:
    volume_name: "config"
    volume_source: "{{vault_config_path}}"
  when: vault_type == "docker"  
- include_tasks: "docker_volume.yml"
  vars:
    volume_name: "logs"
    volume_source: "{{vault_log_path}}"
  when: vault_type == "docker"
- name: "get user id"
  getent:
    database: "passwd"
    key: "{{vault_user}}"
- name: "get group id"
  getent:
    database: "group"
    key: "{{vault_group}}"
- set_fact:
    vault_user_id: "{{getent_passwd[vault_user][1]}}"
    vault_group_id: "{{getent_group[vault_group][1]}}"    
- include_tasks: "docker.yml"
  vars:
    container_name: "{{vault_docker_name}}"
    published_ports:
      - "{{vault_internal_ip}}:{{vault_port}}:8200"
    image: "{{vault_docker_image}}:{{vault_version}}"
    use_command: "server"
    volume:
      - "{{vault_docker_name}}_config:/vault/config"
      - "{{vault_docker_name}}_logs:/vault/logs"
    caps:
      - "IPC_LOCK"
    changed: "{{vault_config.changed or vault_tls_bits.changed}}"
  when: vault_type == "docker"  
