---
- name: "ensure vault config directory exists"
  file:
    path: "{{vault_config_path}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "{{vault_dir_mode}}"
    state: "directory"

- name: "generate configuration"
  template:
    src: "config.hcl"
    dest: "{{vault_config_path}}/config.hcl"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "{{vault_file_mode}}"
  register: vault_config
  no_log: "{{vault_nolog}}"

- name: "create log directory"
  file:
    path: "{{vault_log_path}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "{{vault_log_mode}}"
    state: "directory"

- name: "copy tls bits from vault"
  copy:
    dest: "{{item.dest}}"
    content: "{{lookup('hashi_vault', item.src)}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "0600"
  no_log: "{{vault_nolog}}"
  loop:
    - dest: "{{vault_config_path}}/server.crt"
      src: "{{vault_cert_path}}"
    - dest: "{{vault_config_path}}/server.key"
      src: "{{vault_key_path}}"
  when: vault_cert_source == 'vault'
  register: vault_tls_vault_bits

- name: "copy tls bits from files"
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "0600"
  no_log: "{{vault_nolog}}"
  loop:
    - dest: "{{vault_config_path}}/server.crt"
      src: "{{vault_cert_path}}"
    - dest: "{{vault_config_path}}/server.key"
      src: "{{vault_key_path}}"
  register: vault_tls_file_bits
  when: vault_cert_source == 'file'

- name: "handle tls bits with certbot"
  block:
    - name: "ensure vault_domain is set"
      fail:
        msg: "vault_domain is not set"
      when: vault_domain|default('') == ''

    - name: "install certbot hook"
      template:
        src: "certbot_hook.sh.j2"
        dest: "/etc/letsencrypt/renewal-hooks/deploy/{{letsencrypt_hook_prefix}}vault.sh"
        owner: "root"
        group: "root"
        mode: "0770"

    - name: "check if we have run once"
      stat:
        path: "{{vault_cache}}/certbot_hook-{{vault_domain}}"
      register: vault_certbot_check

    - name: "run once, if needed"
      command: "/etc/letsencrypt/renewal-hooks/deploy/{{letsencrypt_hook_prefix}}vault.sh"

    - name: "mark that we have run once"
      file:
        path: "{{vault_cache}}/certbot_hook-{{vault_domain}}"
        state: "touch"

  when: vault_cert_source == 'letsencrypt'
