---
- name: "install some systemd"
  template:
    src: "vault-systemd.j2"
    dest: "/etc/systemd/system/vault.service"
    owner: "root"
    group: "root"
    mode: "0644"
  register: vault_systemd

- name: "enable and start vault"
  systemd:
    daemon_reload: true
    enabled: "{{ 'true' if vault_startup else 'false' }}"
    state: "{{ 'started' if vault_running else 'stopped' }}"
    name: "vault"
  when: vault_systemd.changed
  register: vault_started

- name: "restart vault if needed"
  systemd:
    daemon_reload: true
    name: "vault"
    state: "restarted"
  when: >
    (vault_config.changed
    or vault_tls_file_bits.changed
    or vault_tls_vault_bits.changed
    or vault_binary_copy.changed)
    and not vault_started.changed
    and vault_running
