---
- name: "ensure vault config directory exists"
  file:
    path: "{{vault_config_path}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "{{vault_dir_mode}}"
    state: "directory"

- name: "generate configuration"
  template:
    src: "config.hcl"
    dest: "{{vault_config_path}}/config.hcl"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "{{vault_config_mode}}"
  register: vault_config

- name: "create log directory"
  file:
    path: "{{vault_log_path}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "{{vault_log_mode}}"
    state: "directory"

- name: "copy tls bits"
  copy:
    src: "{{dotfiles}}/vault/{{vault_cert}}.{{item}}"
    dest: "{{vault_config_path}}/server.{{item}}"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    mode: "{{vault_file_mode}}"
  with_items:
    - "crt"
    - "key"
  register: vault_tls_bits
